// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GeocodeController from "./geocode_controller"
application.register("geocode", GeocodeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MatchController from "./match_controller"
application.register("match", MatchController)

import MatchSubscriptionController from "./match_subscription_controller"
application.register("match-subscription", MatchSubscriptionController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)

import PlayerController from "./player_controller"
application.register("player", PlayerController)
